version: 1
formatters:
  simple_fmt:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple_fmt
    stream: ext://sys.stdout
  console_AAA:
    class: logging.NullHandler
loggers:
  AAA.BBB:
    level: DEBUG
    handlers: [console_AAA]
  root:
    level: DEBUG
    handlers: [console]
disable_existing_loggers: False